version: "3.3"

services:
  db:
    image: mariadb
    command: --max_allowed_packet=1073741824
    ports:
      - ${DB_PORT}:3306
    # volumes:
    # - ./db-data:/var/lib/mysql
    # - ./db-config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      UPLOAD_LIMIT: 2048M
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: db
  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4-fpm-alpine
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_USER_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DEBUG=1
      - WORDPRESS_DEBUG_LOG=1
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress:/var/www/html
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./nginx-includes:/etc/nginx/includes
      - ./wordpress:/var/www/html
    ports:
      - "${NGINX_PORT}:80"
    restart: unless-stopped
volumes:
  wordpress:
